[package]
name = "ghost"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
pretty_assertions = "*"

[dependencies]
anyhow = "1.0.43"
bytes = "1.1.0"
clap = "3.0.0-beta.4"
futures = "0.3.16"
nom = "7.0.0"
reqwest = "0.11.4"
tokio = { version = "1.10.0", features = ["macros"] }
url = "2.2.2"
